version: 2.1
jobs:
  script:
    docker:
      - image: docker.io/healthfinch/circleci-aws:1.0
    steps:
      - checkout
      - run:
          name: "run deploy script"
          command: |
            ./deploy/deploy.rb
          no_output_timeout: 15m
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - script
